// This file is generated by Casasoft Contemporary Carte de Visite Tools
// https://github.com/strawberryfield/Contemporary_CDV

using Casasoft.CCDV;
using Casasoft.CCDV.JSON;
using Mono.Options;
using System.Text.Json;

namespace Route71
{
    internal class CommandLineClass : CommandLine
    {
        public CommandLineClass(string outputname, string desc = "") :
            this(ExeName(), outputname, desc)
        {
        }

        public CommandLineClass(string exename, string outputname, string desc = "") : base(exename, outputname, desc)
        {
            Options = new OptionSet
            {
                // Add your options here
            };
            AddBaseOptions();
        }

        /// <summary>
        /// Text for welcome banner
        /// </summary>
        /// <returns></returns>
        public override string WelcomeBannerText() => $"Casasoft Route71\ncopyright (c) 2023 Roberto Ceccarelli - «The Strawberry Field»\n";

        #region templates
        /// <summary>
        /// Prints a json schema for parameters
        /// </summary>
        /// <returns></returns>
        public override string JsonTemplate()
        {
            ParametersClass p = new();
            return JsonSerializer.Serialize(p, new JsonSerializerOptions { WriteIndented = true });
        }

        /// <summary>
        /// Prints a script template
        /// </summary>
        /// <returns></returns>
        public override string ScriptTemplate()
        {
            ScriptingClass sc = new();
            return base.ScriptTemplate() + sc.Template();
        }
        #endregion
    }
}