// This file is generated by Casasoft Contemporary Carte de Visite Tools
// https://github.com/strawberryfield/Contemporary_CDV

using Casasoft.CCDV.Scripting;

namespace Route71
{
    internal class ScriptingClass : BaseScripting
    {
    }
}